name: partyUNIX
author: zya1lk
version: '0.1'
main: me.zya1lk.partyunix.PartyUNIX
api-version: '1.16'
commands:
  party create:
  party invite:
  party kick:
  party chat:
  party list:
  party leave:

